all: test/mforth test/mforthsimple

test/mforth: MFORTH.h MFORTH.cpp test/mforth.cpp
	c++ -g -I. -lcurses -o $@ -DENABLE_STACK_CHECKING=1 MFORTH.cpp test/mforth.cpp

test/mforthsimple: MFORTH.h MFORTH.cpp test/mforthsimple.cpp
	c++ -g -I. -o $@ -DENABLE_STACK_CHECKING=1 MFORTH.cpp test/mforthsimple.cpp
