all: test/enforth test/enforthsimple

test/enforth: enforth.h enforth.cpp test/enforth.cpp
	c++ -g -I. -lcurses -o $@ -DENABLE_STACK_CHECKING=1 enforth.cpp test/enforth.cpp

test/enforthsimple: enforth.h enforth.cpp test/enforthsimple.cpp
	c++ -g -I. -o $@ -DENABLE_STACK_CHECKING=1 enforth.cpp test/enforthsimple.cpp
