/* NUMSIGN */
BASE, FETCH, UDSLASHMOD, ROT, DUP, CHARLIT, 9, GREATERTHAN, CHARLIT, 7, AND, PLUS, CHARLIT, 48, PLUS, HOLD, EXIT, 0, 0, 0,

/* NUMSIGNGRTR */
DROP, DROP, HLD, FETCH, HERE, HLDEND, PLUS, OVER, MINUS, EXIT, 0, 0,

/* NUMSIGNS */
NUMSIGN, TWODUP, OR, ZBRANCH, 3, BRANCH, -6, EXIT,

/* DOT */
BASE, FETCH, CHARLIT, 10, NOTEQUALS, ZBRANCH, 3, UDOT, EXIT, DUP, ABS, ZERO, LESSNUMSIGN, NUMSIGNS, ROT, SIGN, NUMSIGNGRTR, TYPE, SPACE, EXIT,

/* COLON */
CREATE, CHARLIT, kDefTypeCOLONHIDDEN, CHANGELATESTDEFTYPE, RTBRACKET, EXIT, 0, 0,

/* SEMICOLON */
CHARLIT, EXIT, COMPILECOMMA, CHARLIT, kDefTypeCOLON, CHANGELATESTDEFTYPE, LTBRACKET, EXIT,

/* LESSNUMSIGN */
HERE, HLDEND, PLUS, HLD, STORE, EXIT, 0, 0,

/* TOBODY */
DUP, TOKENQ, ZBRANCH, 4, DROP, ZERO, EXIT, DUP, NFALENGTH, SWAP, TOLFA, ONEPLUS, ONEPLUS, ONEPLUS, PLUS, EXIT,

/* TOIN */
VMADDRLIT, offsetof(EnforthVM, to_in), EXIT, 0,

/* TONUMBER */
DUP, ZBRANCH, 30, OVER, CFETCH, DIGITQ, ZEROEQUALS, ZBRANCH, 3, DROP, EXIT, TOR, TWOSWAP, BASE, FETCH, DUP, TOR, UMSTAR, DROP, SWAP, RFROM, UMSTAR, ROT, PLUS, RFROM, MPLUS, TWOSWAP, CHARLIT, 1, SLASHSTRING, BRANCH, -31, EXIT, 0, 0, 0,

/* ACCEPT */
OVER, PLUS, OVER, KEY, DUP, CHARLIT, 10, NOTEQUALS, ZBRANCH, 15, DUP, TWOOVER, NOTEQUALS, ZBRANCH, 7, EMIT, OVER, CSTORE, ONEPLUS, BRANCH, 2, TWODROP, BRANCH, -20, DROP, NIP, SWAP, MINUS, EXIT, 0, 0, 0,

/* BASE */
VMADDRLIT, offsetof(EnforthVM, base), EXIT, 0,

/* BL */
CHARLIT, ' ', EXIT, 0,

/* COMPILECOMMA */
DUP, TOCOMPILETOKEN, CCOMMA, TOBODY, QDUP, ZBRANCH, 6, VMADDRLIT, offsetof(EnforthVM, dictionary), FETCH, MINUS, WCOMMA, EXIT, 0, 0, 0,

/* CR */
CHARLIT, 10, EMIT, EXIT,

/* CREATE */
BL, PARSEWORD, DUP, ZEROEQUALS, ZBRANCH, 2, ABORT, HERE, VMADDRLIT, offsetof(EnforthVM, dictionary), FETCH, MINUS, WLIT, 0, 128, OR, LATEST, FETCH, WCOMMA, LATEST, STORE, DUP, CHARLIT, 3, LSHIFT, CHARLIT, kDefTypeCREATE, OR, CCOMMA, TUCK, HERE, SWAP, MOVE, ALLOT, ALIGN, EXIT,

/* EXECUTE */
DUP, TOTOKEN, SWAP, TOBODY, PEXECUTE, EXIT, 0, 0,

/* FIND */
COUNT, FINDWORD, EXIT, 0,

/* HERE */
VMADDRLIT, offsetof(EnforthVM, dp), FETCH, EXIT,

/* HEX */
CHARLIT, 16, BASE, STORE, EXIT, 0, 0, 0,

/* HOLD */
HLD, FETCH, ONEMINUS, DUP, HLD, STORE, CSTORE, EXIT,

/* LATEST */
VMADDRLIT, offsetof(EnforthVM, latest), EXIT, 0,

/* LITERAL */
DUP, CHARLIT, 255, INVERT, AND, ZEROEQUALS, ZBRANCH, 7, CHARLIT, CHARLIT, CCOMMA, CCOMMA, BRANCH, 5, CHARLIT, LIT, CCOMMA, COMMA, EXIT, 0,

/* QUIT */
INITRP, ZERO, STATE, STORE, TIB, DUP, TIBSIZE, ACCEPT, SPACE, INTERPRET, CR, STATE, FETCH, ZEROEQUALS, ZBRANCH, 6, PDOTQUOTE, 3, 'o', 'k', ' ', BRANCH, -18, 0,

/* SIGN */
ZEROLESS, ZBRANCH, 4, CHARLIT, '-', HOLD, EXIT, 0,

/* SOURCE */
VMADDRLIT, offsetof(EnforthVM, source_len), TWOFETCH, EXIT,

/* SPACE */
BL, EMIT, EXIT, 0,

/* STATE */
VMADDRLIT, offsetof(EnforthVM, state), EXIT, 0,

/* TYPE */
OVER, PLUS, SWAP, TWODUP, NOTEQUALS, ZBRANCH, 7, DUP, CFETCH, EMIT, ONEPLUS, BRANCH, -9, TWODROP, EXIT, 0,

/* UDOT */
ZERO, LESSNUMSIGN, NUMSIGNS, NUMSIGNGRTR, TYPE, SPACE, EXIT, 0,

/* LTBRACKET */
FALSE, STATE, STORE, EXIT,

/* RTBRACKET */
TRUE, STATE, STORE, EXIT,

/* TODEFTYPE */
TOLFA, ONEPLUS, ONEPLUS, CFETCH, CHARLIT, 7, AND, EXIT,

/* TOLFA */
WLIT, 255, 127, AND, VMADDRLIT, offsetof(EnforthVM, dictionary), FETCH, PLUS, EXIT, 0, 0, 0,

/* TOTOKEN */
DUP, TOKENQ, ZBRANCH, 2, EXIT, DUP, FFIQ, ZBRANCH, 7, FFIARITY, CHARLIT, 232, PLUS, BRANCH, 5, TODEFTYPE, CHARLIT, 224, PLUS, EXIT,

/* TOCOMPILETOKEN */
TOTOKEN, DUP, CHARLIT, 0xe0 - 1, GREATERTHAN, ZBRANCH, 4, CHARLIT, 16, PLUS, EXIT, 0,

/* CHANGELATESTDEFTYPE */
LATEST, FETCH, TOLFA, ONEPLUS, ONEPLUS, CFETCH, CHARLIT, 248, AND, OR, LATEST, FETCH, TOLFA, ONEPLUS, ONEPLUS, CSTORE, EXIT, 0, 0, 0,

/* DIGITQ */
CHARLIT, '0', MINUS, DUP, ZEROLESS, ZBRANCH, 4, DROP, ZERO, EXIT, DUP, CHARLIT, 9, GREATERTHAN, ZBRANCH, 13, DUP, CHARLIT, 17, LESSTHAN, ZBRANCH, 4, DROP, FALSE, EXIT, CHARLIT, 7, MINUS, DUP, ONEPLUS, BASE, FETCH, UGREATERTHAN, ZBRANCH, 4, DROP, FALSE, EXIT, TRUE, EXIT,

/* FFIQ */
TODEFTYPE, CHARLIT, kDefTypeFFI, EQUALS, EXIT, 0, 0, 0,

/* FINDDEF */
TWOTOR, LATEST, FETCH, QDUP, ZBRANCH, 23, DUP, TWORFETCH, ROT, FOUNDDEFQ, ZBRANCH, 13, DUP, TODEFTYPE, CHARLIT, kDefTypeCOLONIMMEDIATE, EQUALS, CHARLIT, 2, AND, ONEMINUS, TWORFROM, TWODROP, EXIT, TOLFA, WFETCH, BRANCH, -24, TWORFROM, TWODROP, FALSE, EXIT,

/* FINDPRIM */
TWOTOR, ZERO, ZERO, DUP, CFETCHNAMES, CHARLIT, 255, NOTEQUALS, ZBRANCH, 27, DUP, TWORFETCH, ROT, FOUNDPRIMQ, ZBRANCH, 14, DROP, CFETCHNAMES, CHARLIT, 128, AND, ZERONOTEQUALS, CHARLIT, 2, AND, ONEMINUS, TWORFROM, TWODROP, EXIT, ROT, ONEPLUS, ROT, DROP, SWAP, BRANCH, -32, TWODROP, TWORFROM, TWODROP, FALSE, EXIT, 0, 0, 0,

/* FINDWORD */
TWODUP, FINDDEF, QDUP, ZBRANCH, 5, TWOSWAP, TWODROP, BRANCH, 8, TWODUP, FINDPRIM, DUP, ZBRANCH, 3, TWOSWAP, TWODROP, EXIT, 0, 0, 0,

/* FOUNDDEFQ */
DUP, TODEFTYPE, CHARLIT, kDefTypeCOLONHIDDEN, EQUALS, ZBRANCH, 5, DROP, TWODROP, FALSE, EXIT, TWODUP, NAMELENGTH, NOTEQUALS, ZBRANCH, 5, DROP, TWODROP, FALSE, EXIT, DUP, FFIQ, ZBRANCH, 5, DROP, TWODROP, FALSE, EXIT, TOLFA, ONEPLUS, ONEPLUS, ONEPLUS, OVER, ICOMPARE, ZEROEQUALS, EXIT,

/* FOUNDPRIMQ */
DUP, DUP, CFETCHNAMES, CHARLIT, 127, AND, PLUS, ONEPLUS, TOR, DUP, CFETCHNAMES, CHARLIT, 127, AND, ROT, NOTEQUALS, ZBRANCH, 5, TWODROP, RFROM, FALSE, EXIT, ONEPLUS, OVER, CFETCH, OVER, CFETCHNAMES, NOTEQUALS, ZBRANCH, 5, TWODROP, RFROM, FALSE, EXIT, ONEPLUS, SWAP, ONEPLUS, SWAP, DUP, RFETCH, EQUALS, ZBRANCH, -19, TWODROP, RFROM, TRUE, EXIT, 0,

/* HLD */
VMADDRLIT, offsetof(EnforthVM, hld), EXIT, 0,

/* HLDEND */
CHARLIT, kEnforthCellSize * 8 * 3, EXIT, 0,

/* INTERPRET */
VMADDRLIT, offsetof(EnforthVM, source_len), TWOSTORE, ZERO, TOIN, STORE, BL, PARSEWORD, DUP, ZBRANCH, 37, FINDWORD, QDUP, ZBRANCH, 14, ONEPLUS, STATE, FETCH, ZEROEQUALS, OR, ZBRANCH, 4, EXECUTE, BRANCH, 21, COMPILECOMMA, BRANCH, 18, NUMBERQ, ZBRANCH, 8, STATE, FETCH, ZBRANCH, 11, LITERAL, BRANCH, 8, TYPE, SPACE, CHARLIT, '?', EMIT, CR, ABORT, BRANCH, -40, TWODROP, EXIT, 0, 0, 0,

/* NAMELENGTH */
TOLFA, ONEPLUS, ONEPLUS, CFETCH, CHARLIT, 3, RSHIFT, EXIT,

/* NFALENGTH */
DUP, FFIQ, ZBRANCH, 5, DROP, ZERO, BRANCH, 8, TOLFA, ONEPLUS, ONEPLUS, CFETCH, CHARLIT, 3, RSHIFT, EXIT,

/* NUMBERQ */
ZERO, ZERO, TWOSWAP, TONUMBER, TWODROP, DROP, TRUE, EXIT,

/* PARSEWORD */
TOR, SOURCE, TOIN, FETCH, SLASHSTRING, RFETCH, TOR, OVER, CFETCH, RFETCH, EQUALS, OVER, AND, ZBRANCH, 6, CHARLIT, 1, SLASHSTRING, BRANCH, -12, RFROM, DROP, OVER, SWAP, RFROM, TOR, OVER, CFETCH, RFETCH, NOTEQUALS, OVER, AND, ZBRANCH, 6, CHARLIT, 1, SLASHSTRING, BRANCH, -12, RFROM, TWODROP, DUP, SOURCE, DROP, MINUS, TOIN, STORE, OVER, MINUS, EXIT, 0, 0,

/* TIB */
VMADDRLIT, offsetof(EnforthVM, tib), EXIT, 0,

/* TIBSIZE */
CHARLIT, 80, EXIT, 0,

/* TOKENQ */
WLIT, 0, 128, AND, ZEROEQUALS, EXIT, 0, 0,

